### ISSUE TITLE
Issue with kmspc function

### ISSUE THREAD

**Issue by Biometrika** [PPaccioretti/paar#8]
Dear Dr. Paccioretti,

I am encountering an issue with the kmspc() function when applied to a dataset.
The error message is:

Error in names(auxi) <- paste("CS", agarder, sep = "") :
'names' attribute [8] must be the same length as the vector [7]

Could you please advise on why this issue might be occurring specifically with my dataset, and what adjustments could resolve it?

Many thanks in advance!

**Comment by PPaccioretti** [comment]
Hello, 
Could you please provide more context? What argument are you using? If you can provide a [Reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example/16532098) it might help me to find the problem. 
Thank you!

**Comment by Biometrika** [comment]
Dear Dr Paccioretti,
thanks a lot for your fast response. The data is proprietary, so I am unable to share it publicly. I am sending you the data and the script to your email available on the GitHub page.
